(* HTMX attribute helpers for use with the [attrs] escape hatch on Ocelot components.

   Usage:
   <Ocelot.Button attrs=[Hx.get "/api/click"; Hx.target "#result"]> "Click" </Ocelot.Button>
*)

(* Core attributes *)
let get url = ("hx-get", `String url)
let post url = ("hx-post", `String url)
let put url = ("hx-put", `String url)
let delete_ url = ("hx-delete", `String url)
let patch url = ("hx-patch", `String url)
let trigger event = ("hx-trigger", `String event)
let target selector = ("hx-target", `String selector)
let swap mode = ("hx-swap", `String mode)
let select selector = ("hx-select", `String selector)
let select_oob selector = ("hx-select-oob", `String selector)
let swap_oob value = ("hx-swap-oob", `String value)
let vals json = ("hx-vals", `String json)
let include_ selector = ("hx-include", `String selector)
let indicator selector = ("hx-indicator", `String selector)
let confirm message = ("hx-confirm", `String message)
let disable = ("hx-disable", `Bool true)
let disinherit value = ("hx-disinherit", `String value)
let encoding value = ("hx-encoding", `String value)
let ext name = ("hx-ext", `String name)
let headers json = ("hx-headers", `String json)
let history value = ("hx-history", `String value)
let params value = ("hx-params", `String value)
let sync value = ("hx-sync", `String value)
let validate = ("hx-validate", `Bool true)
let preserve = ("hx-preserve", `Bool true)
let prompt message = ("hx-prompt", `String message)
let replace_url value = ("hx-replace-url", `String value)
let request value = ("hx-request", `String value)
let boost = ("hx-boost", `Bool true)

(* SSE extension *)
let sse_connect url = ("sse-connect", `String url)
let sse_swap event = ("sse-swap", `String event)
let sse_close event = ("sse-close", `String event)

(* WebSocket extension *)
let ws_connect url = ("ws-connect", `String url)
let ws_send = ("ws-send", `Bool true)

(* Class tools extension *)
let classes value = ("classes", `String value)

(* Preload extension *)
let preload value = ("preload", `String value)

(* Path deps extension *)
let path_deps value = ("path-deps", `String value)

(* Loading states extension *)
let loading = ("data-loading", `Bool true)
let loading_class value = ("data-loading-class", `String value)
let loading_class_remove value = ("data-loading-class-remove", `String value)
let loading_disable = ("data-loading-disable", `Bool true)
let loading_aria_busy = ("data-loading-aria-busy", `Bool true)
let loading_delay value = ("data-loading-delay", `String value)
let loading_target selector = ("data-loading-target", `String selector)
let loading_path value = ("data-loading-path", `String value)
let loading_states = ("data-loading-states", `Bool true)
